// src/app/component/about-me/about-me.component.ts
import { Component, Input } from '@angular/core';


@Component({
  selector: 'about-me',
  template: `
  <div class="container">
      <div id="aboutme" class="col-lg-12">
        <h2>About me</h2>
  	    <h4 id="aboutmeparts" *ngFor="let paragraph of aboutMeParagraphs">{{paragraph}}</h4>
      </div>
  </div>
  `
})
export class AboutMeComponent {
  @Input() aboutMeParagraphs: string[];

}

// src/components/AboutMe/AboutMe.tsx
import React, { FC } from 'react';
import './AboutMe.scss';
import { DANIEL } from '../../static-daniel.service';

interface AboutMeProps {}

// function to generate the about me paragraphs
const generateAboutMeParagraphs = () => {
  const aboutMeParagraphs = [];
  for (const paragraph of DANIEL.aboutMeParagraphs) {
    aboutMeParagraphs.push(
      <p className="aboutme-paragraph" key={paragraph}>
        {paragraph}
      </p>
    );
  }
  return aboutMeParagraphs;
};

const AboutMe: FC<AboutMeProps> = () => (
  <div className="container">
    <div id="aboutme">
      <h2 id="aboutme-title">About me</h2>
      <div id="aboutme-paragraphs">
        <div id="aboutmeparts">{generateAboutMeParagraphs()}</div>
      </div>
    </div>
  </div>
);

export default AboutMe;
